env:
  matrix:
    - PF_BUILD=cmake

language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
os:
  - linux
addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
    - cmake

before_install:
  - echo $LANG
  - echo $LC_ALL
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran
  - sudo apt-get install -y libhypre-2.8.0b libhypre-dev
  - sudo apt-get install -y libhdf5-openmpi-dev libhdf5-openmpi-7 hdf5-helpers
  - sudo apt-get install -y tcl-dev tk-dev
  - sudo apt-get install -y openmpi-bin openmpi-doc libopenmpi-dev
  - if [[ ! -f cmake-3.9.0-Linux-x86_64/bin/cmake ]]; then wget --no-check-certificate http://cmake.org/files/v3.9/cmake-3.9.0-Linux-x86_64.tar.gz && tar -xvf cmake-3.9.0-Linux-x86_64.tar.gz; fi

before_script:
  - cd $TRAVIS_BUILD_DIR
  - export PARFLOW_SRC_DIR=$TRAVIS_BUILD_DIR
  - export PARFLOW_DIR=$TRAVIS_BUILD_DIR/install
  - mkdir -p $PARFLOW_DIR
  - wget https://wci.llnl.gov/content/assets/docs/simulation/computer-codes/silo/silo-4.10.2/silo-4.10.2.tar.gz
  - tar -xf silo-4.10.2.tar.gz
  - (cd silo-4.10.2 && ./configure  --prefix=$PARFLOW_DIR --disable-silex --disable-hzip --disable-fpzip && make install)
  - export CC=mpicc
  - export CXX=mpiCC
  - export F77=mpif77
  - export FC=mpif90
  - echo "PF_BUILD = $PF_BUILD"
  - (mkdir -p build && cd build && ../cmake-3.9.0-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS='-Wall -Werror -Wno-unused-result -Wno-unused-function' -DPARFLOW_AMPS_LAYER=mpi1 -DPARFLOW_AMPS_SEQUENTIAL_IO=true -DPARFLOW_ENABLE_TIMING=TRUE -DPARFLOW_HAVE_CLM=ON -DPARFLOW_ENABLE_HYPRE=true -DPARFLOW_ENABLE_HDF5=true -DSILO_ROOT=$PARFLOW_DIR -DCMAKE_INSTALL_PREFIX=$PARFLOW_DIR .. )
  - (cd build && make && make install)

  